[package]
name = "ac1"
version = "0.1.0"
authors = ["artie <atch.cpp@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cursive = "0.14"
#rand = "0.7"
cursive_table_view = "0.12"
chrono = "^0.4"